import type React from "react";

const monoFontStack =
  "var(--font-plex-mono), 'IBM Plex Mono', monospace";

const baseBlock = {
  background: "transparent",
  fontFamily: monoFontStack,
  fontSize: "14px",
  lineHeight: "1.6",
};

export const darkTheme: { [key: string]: React.CSSProperties } = {
  'pre[class*="language-"]': {
    ...baseBlock,
    color: "#e8e3d6",
    margin: 0,
    padding: 0,
  },
  'code[class*="language-"]': {
    ...baseBlock,
    color: "#e8e3d6",
  },
  comment: { color: "#74706a", fontStyle: "italic" },
  prolog: { color: "#74706a" },
  doctype: { color: "#74706a" },
  cdata: { color: "#74706a" },
  punctuation: { color: "#9c978d" },
  property: { color: "#e0a060" },
  tag: { color: "#e0a060" },
  boolean: { color: "#e0a060" },
  number: { color: "#e0a060" },
  constant: { color: "#e0a060" },
  symbol: { color: "#e0a060" },
  deleted: { color: "#e0a060" },
  selector: { color: "#a8c98e" },
  "attr-name": { color: "#a8c98e" },
  string: { color: "#a8c98e" },
  char: { color: "#a8c98e" },
  builtin: { color: "#a8c98e" },
  inserted: { color: "#a8c98e" },
  operator: { color: "#9c978d" },
  entity: { color: "#9c978d", cursor: "help" },
  url: { color: "#9c978d" },
  variable: { color: "#e8e3d6" },
  atrule: { color: "#cba6f7" },
  "attr-value": { color: "#a8c98e" },
  function: { color: "#cba6f7" },
  "class-name": { color: "#cba6f7" },
  keyword: { color: "#f0a8a8" },
  regex: { color: "#e0a060" },
  important: { color: "#f0a8a8", fontWeight: "bold" },
  bold: { fontWeight: "bold" },
  italic: { fontStyle: "italic" },
};

export const lightTheme: { [key: string]: React.CSSProperties } = {
  'pre[class*="language-"]': {
    ...baseBlock,
    color: "#0e0f11",
    margin: 0,
    padding: 0,
  },
  'code[class*="language-"]': {
    ...baseBlock,
    color: "#0e0f11",
  },
  comment: { color: "#7a7f86", fontStyle: "italic" },
  prolog: { color: "#7a7f86" },
  doctype: { color: "#7a7f86" },
  cdata: { color: "#7a7f86" },
  punctuation: { color: "#3d4147" },
  property: { color: "#a06020" },
  tag: { color: "#a06020" },
  boolean: { color: "#a06020" },
  number: { color: "#a06020" },
  constant: { color: "#a06020" },
  symbol: { color: "#a06020" },
  selector: { color: "#1f5d3b" },
  "attr-name": { color: "#1f5d3b" },
  string: { color: "#1f5d3b" },
  char: { color: "#1f5d3b" },
  builtin: { color: "#1f5d3b" },
  operator: { color: "#3d4147" },
  variable: { color: "#0e0f11" },
  atrule: { color: "#7c3aed" },
  "attr-value": { color: "#1f5d3b" },
  function: { color: "#7c3aed" },
  "class-name": { color: "#7c3aed" },
  keyword: { color: "#b91c4f" },
  regex: { color: "#a06020" },
  important: { color: "#b91c4f", fontWeight: "bold" },
};
